name: jmsharp.net
favicon: null
layout_spectrum: 0.6097406374756247
typography_spectrum: 0.4148391087073833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4704195763915777
  lightness: 0.6642734981141984
  saturation: 0.7528007130604237
  rhythmicContrast: 0.02896339911967516
purpose: []
